# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages-thorchain.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'messages-thorchain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18messages-thorchain.proto\x1a\x0btypes.proto\"O\n\x13ThorchainGetAddress\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x14\n\x0cshow_display\x18\x02 \x01(\x08\x12\x0f\n\x07testnet\x18\x03 \x01(\x08\"#\n\x10ThorchainAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\xbb\x01\n\x0fThorchainSignTx\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x1a\n\x0e\x61\x63\x63ount_number\x18\x02 \x01(\x04\x42\x02\x30\x01\x12\x10\n\x08\x63hain_id\x18\x03 \x01(\t\x12\x12\n\nfee_amount\x18\x04 \x01(\r\x12\x0b\n\x03gas\x18\x05 \x01(\r\x12\x0c\n\x04memo\x18\x06 \x01(\t\x12\x14\n\x08sequence\x18\x07 \x01(\x04\x42\x02\x30\x01\x12\x11\n\tmsg_count\x18\x08 \x01(\r\x12\x0f\n\x07testnet\x18\t \x01(\x08\"\x15\n\x13ThorchainMsgRequest\"Y\n\x0fThorchainMsgAck\x12\x1f\n\x04send\x18\x01 \x01(\x0b\x32\x11.ThorchainMsgSend\x12%\n\x07\x64\x65posit\x18\x02 \x01(\x0b\x32\x14.ThorchainMsgDeposit\"\x80\x01\n\x10ThorchainMsgSend\x12\x14\n\x0c\x66rom_address\x18\x06 \x01(\t\x12\x12\n\nto_address\x18\x07 \x01(\t\x12\x12\n\x06\x61mount\x18\x08 \x01(\x04\x42\x02\x30\x01\x12(\n\x0c\x61\x64\x64ress_type\x18\t \x01(\x0e\x32\x12.OutputAddressTypeJ\x04\x08\n\x10\x0b\"V\n\x13ThorchainMsgDeposit\x12\r\n\x05\x61sset\x18\x01 \x01(\t\x12\x12\n\x06\x61mount\x18\x02 \x01(\x04\x42\x02\x30\x01\x12\x0c\n\x04memo\x18\x03 \x01(\t\x12\x0e\n\x06signer\x18\x04 \x01(\t\":\n\x11ThorchainSignedTx\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x42\x35\n\x1a\x63om.keepkey.deviceprotocolB\x17KeepKeyMessageThorchain')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_thorchain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.keepkey.deviceprotocolB\027KeepKeyMessageThorchain'
  _globals['_THORCHAINSIGNTX'].fields_by_name['account_number']._loaded_options = None
  _globals['_THORCHAINSIGNTX'].fields_by_name['account_number']._serialized_options = b'0\001'
  _globals['_THORCHAINSIGNTX'].fields_by_name['sequence']._loaded_options = None
  _globals['_THORCHAINSIGNTX'].fields_by_name['sequence']._serialized_options = b'0\001'
  _globals['_THORCHAINMSGSEND'].fields_by_name['amount']._loaded_options = None
  _globals['_THORCHAINMSGSEND'].fields_by_name['amount']._serialized_options = b'0\001'
  _globals['_THORCHAINMSGDEPOSIT'].fields_by_name['amount']._loaded_options = None
  _globals['_THORCHAINMSGDEPOSIT'].fields_by_name['amount']._serialized_options = b'0\001'
  _globals['_THORCHAINGETADDRESS']._serialized_start=41
  _globals['_THORCHAINGETADDRESS']._serialized_end=120
  _globals['_THORCHAINADDRESS']._serialized_start=122
  _globals['_THORCHAINADDRESS']._serialized_end=157
  _globals['_THORCHAINSIGNTX']._serialized_start=160
  _globals['_THORCHAINSIGNTX']._serialized_end=347
  _globals['_THORCHAINMSGREQUEST']._serialized_start=349
  _globals['_THORCHAINMSGREQUEST']._serialized_end=370
  _globals['_THORCHAINMSGACK']._serialized_start=372
  _globals['_THORCHAINMSGACK']._serialized_end=461
  _globals['_THORCHAINMSGSEND']._serialized_start=464
  _globals['_THORCHAINMSGSEND']._serialized_end=592
  _globals['_THORCHAINMSGDEPOSIT']._serialized_start=594
  _globals['_THORCHAINMSGDEPOSIT']._serialized_end=680
  _globals['_THORCHAINSIGNEDTX']._serialized_start=682
  _globals['_THORCHAINSIGNEDTX']._serialized_end=740
# @@protoc_insertion_point(module_scope)
